name: security-scan
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

permissions:
  contents: read
  actions: read
  checks: write
  pull-requests: write
  id-token: write
 
jobs:
  secret-audit:
    name: "Secrets Scan"
    uses: YAtechnologies/cross-github-actions/.github/workflows/secrets-audit.yaml@main
    secrets: inherit
    with:
      defectdojo-product-type: pi-cloudops-squad
      defectdojo-product: yassir-mobility-cloud
      defectdojo-engagement-name: pi-terraform-modules
      project_id: ${{ vars.SEC_GCP_PROJECT_NAME }}
      workload_identity_provider: ${{ vars.SEC_WIP_GCP_ARTIFACT_STORAGE }}
      service_account: ${{ vars.SEC_WIP_GCP_ARTIFACT_STORAGE_SVC_ACCT }}
      artifact_storage_bucket: ${{ vars.GCP_ARTIFACT_STORAGE_BUCKET }}
  Security-Scan:
    name: Security Scan
    uses: YAtechnologies/cross-github-actions/.github/workflows/oss-scan.yaml@main
    secrets: inherit
    with:
      defectdojo-product-type: pi-cloudops-squad
      defectdojo-product: yassir-mobility-cloud
      defectdojo-engagement-name: pi-terraform-modules
      project_id: ${{ vars.SEC_GCP_PROJECT_NAME }}
      workload_identity_provider: ${{ vars.SEC_WIP_GCP_ARTIFACT_STORAGE }}
      service_account: ${{ vars.SEC_WIP_GCP_ARTIFACT_STORAGE_SVC_ACCT }}
      artifact_storage_bucket: ${{ vars.GCP_ARTIFACT_STORAGE_BUCKET }}